### ISSUE TITLE
Mastery definition

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#11]
In section 1.3:

> Mastery: People work best when they are always learning

Feedback:

> This needs to be balanced with the idea that people work best when they have already mastered the skills required to do the job. Also learning takes time and effort and increases cognitive load - people cannot be learning all of the time.

**Comment by arctangent** [comment]
The point re cognitive load is somewhat valid, however the term is usually used in the context of limiting the _number of things_ one has to learn about. It is reasonable to assume a developer might always be learning about Python, but not reasonable for them to be required to learn about 42 different technologies at the same time. Having said that, perhaps "always learning" does sound a little bit too intense.

Proposed action:

* Change wording to "...when they have frequent learning opportunities"

**Comment by SeanCraig** [comment]
I think this links to most of our themes. People do their best work when:
They understand the PURPOSE and value of what they are doing
They have AUTONOMY to decide how best to tackle it
They have the MASTERY to know or can add to their knowledge by learning how to implement it
They work in an environment with good FLOW that has little or no friction for deployment
They have the TELEMETRY to measure the impact of their work.
