### ISSUE TITLE
Continuous delivery and happy users

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#14]
In section 1.4:

> Users are happy when value is delivered continuously

Feedback:

> I've generally found that most users are oblivious to continuous delivery of value, they just want a high quality working product, they are generally not too concerned about how it is delivered.

**Comment by arctangent** [comment]
I'm not sure I follow the logic here. If users want a high quality working product then by definition they're not happy until they get it, which will take longer if it isn't delivered continuously.

Proposed action:

* Rewrite to make clearer e.g. by adding "...so that they can enjoy that value immediately"
* Explain how continuous delivery benefits users
* Explain how continuous delivery benefits NHSUK (through driving other best practices)
* Explore the above in coaching sessions

**Comment by SeanCraig** [comment]
Again worried about the mindset expressed here.
It doesn't sound like we have done enough to explain the benefits of MVP, progressive enhancement, "little and often" etc.

**Comment by arctangent** [comment]
Added some things to separate list of coaching topics
