### ISSUE TITLE
Sprint Planning and delivery cadence

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#17]
In section 3.1.1:

> ensure the solution is delivered incrementally, with a deployment each sprint... write code which is deployed to production at least once per sprint

Feedback:

> Rules like this tend to lead to reduced flexability for individuals and/or 'deployment for the sake of deployment'. We'd have to get agreement (probably at sprint planning) for at least 1 ticket which will give a high probability of code being deployed, will this always fit with business needs?

**Comment by arctangent** [comment]
I'm not sure I follow the logic here. We should be deploying frequently in order to provide value to users as early as possible, and to drive adoption of better development practices.

Proposed action:

* Use coaching sessions to explore the reasons why we would want to deploy frequently
* Consider changing the wording from "write code" to "create value"?

**Comment by snehal-vahule** [comment]
this might direct us in breaking down stories properly and not having one huge taks that cant be completed in two weeks.

**Comment by SeanCraig** [comment]
Again I'm worried about the mindset expressed here. Coaching is one approach but might need to be supported by more education as well. Teach people what good looks like for us and then coach them to achieve it

**Comment by arctangent** [comment]
Resolution:

* No action required (in this repository)
* In another currently open issue we record the need to share a link to the EQF on Confluence
* The EQF contains the relevant “education” e.g. https://github.com/NHSDigital/software-engineering-quality-framework/blob/master/patterns/little-and-often.md
