### ISSUE TITLE
Code Review - checklist

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#18]
In section 3.1.1:

> ensure your team is following a code review checklist

Feedback:

> do we have a code review checklist documented anywhere?

**Comment by arctangent** [comment]
Proposed action:

* This is a question each Senior Developer should ask within their current delivery team
* If they don't have one, then the team should agree one
* SDMT may also wish to consider publishing a best practices guide

**Comment by snehal-vahule** [comment]
code review checklist should be on "Dot net standards" wiki
https://dev.azure.com/nhsuk/dotnet-standards/_wiki/wikis/dotnet-standards/210/Home

**Comment by sikanderakbarali** [comment]
Is it it worth having a standard checklist that doesnt have to adhere to a certain tech stack? A checklist which is generic and works with any coding language

**Comment by arctangent** [comment]
Resolution:

* No action for us here
* Senior Devs can figure out how checklists would best work within and across the delivery teams
