### ISSUE TITLE
Deployment frequency - where does responsibility lie?

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#2]
On the one hand, I have written that developers should:

> commit code which is deployed to production at least once per sprint

On the other hand, Sikander has pointed out:

> This also will have a dependency on how often that particular team deploys to production. If they only deploy once a month or once every 6 weeks then it wont be possible to deploy a developers code to production once per sprint. We also need to take into account any dependencies a ticket will have on other tickets i.e embargoed release

One way I could address this is to say that developers should:

> commit code which is merged to the main branch at least once per sprint

But then how are we encouraging our development teams to deploy more frequently?

**Comment by SeanCraig** [comment]
Maybe we need to explain the Lean concept of inventory as waste?

**Comment by arctangent** [comment]
Resolution:

* Will leave text as-is
* Have added Lean topics as suggestions for coaching
