### ISSUE TITLE
Mastery - distribution of expertise

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#23]
Feedback on section 1.3:

> Mastery - mostly agree, but we need a certain level of expertise in each area, before we can give others the chance to grow into these areas. We need to be clear to the business that 'constantly' learning means potentially slower delivery. Also if no-one is a 'master' in certain areas (e.g. Dev Ops pipelines, terraform) then we won't have anyone to learn from or to evaluate what constitutes 'best practise'.

**Comment by arctangent** [comment]
I believe the first point is saying that Senior Devs need expertise in certain areas before they can give others the chance to gain expertise there. I don't think I agree with that, but Seniors should certainly learn the ability to "broadly" oversee others who are "going deep".

The second point is correct: we do need to be clear that (1) there are benefits to having a well-trained workforce, (2) that achieving this comes with some cost to delivery speed.

Regarding the third point, yes we do need to ensure that some developers attain something close to "mastery" in various areas. This is the reason we are emphasising Mastery as a goal.

Proposed action:

* Explain via coaching how allowing others to grow helps the whole team deliver more
* Sean to ensure DMs understand the strategic trade-offs
* Check where we are with our list of Key Skills and ask Senior Devs to propose further action

**Comment by SeanCraig** [comment]
Yep. We need to revisit and refresh the skills work so we can plan around this

**Comment by arctangent** [comment]
Resolution:

* Key Skills added to DTLT agenda for 11/10/21
* Finite vs Infinite Games added to list of proposed coaching topics
