### ISSUE TITLE
Purpose - conflicts with business needs and resourcing issues

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#24]
Feedback on section 1.3:

> Purpose - to me this conflicts with the needs of the business and resourcing issues. Choice is good to an extent, but there needs to be a balance to ensure deliverables are achieved at a reasonable pace. And if people have skills in certain areas, why are we not utilising them effectively.

**Comment by arctangent** [comment]
This would be true if we were playing a "finite game" (e.g. team delivers a single product to a client then leaves) but we would like Senior Developers to understand that we are playing an "infinite game". The NHSUK dev team needs to optimise also for its continued ability through time to keep delivering against many products.

Proposed action:

* Use coaching to examine the how this longer and more holistic view of engineering changes how we might wish to behave during a single project (or assignment to a product team)
* Good analogy is the concept of a sacrifice in the game of chess - a short-term exchange leaves you "behind" but as a result you achieve a long-term strategic advantage that keeps you "ahead". (Same thing as allowing a dev to try something new instead of the Senior Dev "doing the hard bit")

**Comment by SeanCraig** [comment]
I think there are two parts to this comment that need to be addressed separately.
Firstly re choice. I agree but in my view there is no balance atm and what we are doing is seeking to address this. 
Secondly re skill utilisation. One of our key goals is to level up our capability. The business expects us to rise to meet the increasing challenges ahead. We cannot do that sustainably without an empowered, and engaged team.

**Comment by arctangent** [comment]
- I've added a note to TWWW to ensure we discuss the balance between personal and business objectives.
- We have a separate action to discuss our Key Skills work
- I've added a relevant coaching topic to my list
