### ISSUE TITLE
Measuring - how?

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#25]
Feedback on section 1.4:

> Are we going to be monitored on our commit frequency?

**Comment by arctangent** [comment]
Our guidance states:

> The leadership team will monitor how often developers are able to contribute code which is deployed to production.

Perhaps the question is implicitly asking us if we mean that "developers" will be monitored rather than "teams".

Proposed action:

* Change wording to "...how often teams are able..."

**Comment by sikanderakbarali** [comment]
We could say that we are going to monitor how often teams commit code and how often they deploy. All links back to the engineering quality assessment.

**Comment by SeanCraig** [comment]
We want to focus on the team as that is the unit of delivery. If a team isn't deploying often then we would look into the causes of that which may include commit patterns of devs along with lots of other reasons.
