### ISSUE TITLE
Continuous Delivery - why?

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#26]
Feedback on section 1.4:

> Do end users care about CD/CI etc, they only care about working end product. Is this more reflective of what PO's / UR think? For me, New features - good, Constantly changing existing features - not good user experience. Releasing every sprint, will this be a requirement or an aspiration? Not always possible to release every sprint without gaming / compromising the actual real priorities.

**Comment by arctangent** [comment]
There are two key reasons for continuous delivery that we need to make clearer to developers:

1. It is mainly about delivering value early so that users can enjoy that value and so that we can get feedback as early as possible
2. CD is a driver of better engineering practices and is worth pursuing in its own right

Proposed actions:

* Explore the reasons for CD in coaching sessions
* Consider re-wording the relevant part of section 1.4 as mentioned already in https://github.com/arctangent-nhsuk/the-way-we-work/issues/14

**Comment by SeanCraig** [comment]
Wow. Not sure with where to start with with one. Maybe a pointer towards benefits of MVP and iterative progressive enhancement.
I also think that there is a danger that some teams iterate small slices for too long and don't measure the value of the next story to enhance the current feature against the first story of the next one.

**Comment by snehal-vahule** [comment]
issue mentions "constantly changing requirements"... is it worth looking into it, if any project/team is facing this issue. It means PO is not being able to bring confirmed user requirements to the board. or the reason for this maybe.

**Comment by arctangent** [comment]
Resolution:

* No action required (in this repo)
* Suggested coaching topics now include continuous delivery
