### ISSUE TITLE
Code Review - clarification request

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#28]
Feedback:

> Code Review (is this part of feature development or does it need to be a separate item?)

**Comment by arctangent** [comment]
I think we have shown Code Review as being a constituent part of Feature Development in section 3.1.1. However, perhaps we need to be clearer about the purpose of section 3.

Proposed action:

* Amend the intro to section 3 to read: "This section lists the key **activities and associated** best practices required within each of the responsibility areas."

**Comment by sikanderakbarali** [comment]
I agree with it being part of feature development. Its crucial that every change we make in the code is code reviewed
