### ISSUE TITLE
Coaching - more info requested

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#29]
Feedback:

> Coaching? Can we have a definition, and how is this to be implemented

**Comment by arctangent** [comment]
Proposed action:

* Jacob to provide information shortly

**Comment by SeanCraig** [comment]
Perhaps something along the lines of https://www.performanceconsultants.com/the-purpose-of-coaching

**Comment by arctangent** [comment]
No action required (in this repo). Jacob to confirm coaching agenda in due course.
