### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#30]
Feedback:

> Will we receive mentoring / LM training?

**Comment by arctangent** [comment]
Line Management:

Senior Developers should already have attended relevant line management training (and if not their Principal can guide them towards it). Do we have a record of who has attended it? All line managers should also have been invited to the Management Matters events. Have they been attending it?

Mentoring:

Do we believe that formal mentoring training is necessary in order to transfer technical knowledge?

Proposed action:

* Decide what training we think is appropriate and ensure we can provide it
* Principals to assess training needs and approve training requests as appropriate

**Comment by SeanCraig** [comment]
Mentoring shouldn't require formal training.

**Comment by arctangent** [comment]
Resolution:

* No action required (in this repository)
* Principals to assess training needs and recommend/approve training courses as usual
