### ISSUE TITLE
Prioritisation

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#32]
Feedback on section 3.1:

> Sprint prioritisation should be driven by business needs (PO), not developer preference? How do we balance this with the need to do preparatory / spike work to deal with complex tech enablers that needs additional up-front work.

**Comment by arctangent** [comment]
In theory our Product Owners should be able to represent the true business needs. However, in practice they lack the technical expertise to be able to make informed decisions about the importance of work which is not user-facing. Developers have a responsibility to educate the PO about the importance of this other work, and since it is the developers who must "commit" to the contents of a sprint backlog they really do have freedom to choose how the solution is delivered.

Proposed action:

* Sean to evangelise on behalf of developers to ensure POs (and DMs) understand why there is often a need to carry out work "out of sequence" and why there should be technical features in the backlog as well as user stories

**Comment by SeanCraig** [comment]
Yes need to get SLT support as part of this. I would say technical user stories but its just semantics

**Comment by arctangent** [comment]
Resolution:

* Sean to evangelise
