### ISSUE TITLE
Corner-cutting

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#34]
Feedback on section 3.1.2

> There are many areas in the EQ Framework that we don't have the resources or tools to do effectively - such as performance testing, security based testing, accessibility testing. We often have to deploy code to production with some of these areas neglected or an element of risk attached. Are we expected to slow down the pace of delivery to ensure that all the areas of the EQF are met for new software deployed to production? Is the business on board with this? Do we delay releases until all the aspects of the EQF are met?

**Comment by arctangent** [comment]
My view is that the EQF specifies the required quality and standard(s) of our work. We aren't "slowing down" if we follow this guidance, we are simply "doing the work correctly". The EQF has come from the Head of Engineering and so, yes, the business is on board. It simply isn't acceptable to prioritise speed of delivery over everything else (although we do acknowledge there were different priorities during the pandemic).

Proposed action:

* Put in place a mechanism (similar to Architecture Decision Records) by which a team can propose to cut corners if they feel they really have to. Perhaps overseen by TAB, and with a requirement for a Risk to be formally recorded (along with how it will be Remediated in the short term).

**Comment by SeanCraig** [comment]
There was a discussion about this at the EQF retro yesterday where I proposed making EQF part of the service readiness process. There is also some work ongoing on security assurance which might also encompass perf testing etc.
Teams cannot ignore areas of the framework for new services, caveats could be agreed if we do need to release quickly but I imagine that as part of any such agreement a remediation plan would emerge.

**Comment by arctangent** [comment]
Resolution:

* Update 3.1.2 System Design and Documentation
* Exceptions to be discussed at TAB and recorded on the dashboard

**Comment by arctangent** [comment]
Closed by https://github.com/arctangent-nhsuk/the-way-we-work/commit/62f1d59f5173578b622a733e15e939f18a54eda3
