### ISSUE TITLE
Timing of 121 meetings

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#35]
Feedback:

> meeting at sprint start etc, do we need to do this, would create a slow start to sprint? should we not already have sufficient work lined up before sprint planning etc? Maybe the wording of this section needs to change a little to reflect our planning processes. i.e. day 1 of the sprint is not the day to be deciding if we have enough work for the sprint. This analysis and elaboration should already have been done?

**Comment by arctangent** [comment]
We have acknowledged in the Quick Guide for DMs and POs that there may appear to be a "slow start" to sprints if all 121s take place on the first day of the sprint. I see no problem with a "slow start" in principle.

There is some confusion evident in the rest of the feedback that we could help to clear up.

Proposed action:

* Add into section 3.4.2 a bullet explaining that if a line manager discovers their report does not have enough/any work planned in their next sprint then they should meet with their report and the DM to move extra items into the sprint i.e. what is the corrective measure
* Consider discussing Nudge Theory in coaching sessions (or, as mentioned elsewhere, the difference between finite and infinite games)

**Comment by snehal-vahule** [comment]
i propose that 1-2-1s dosent have to be on frist day of sprint.

**Comment by sikanderakbarali** [comment]
As long as we have 1-2-1s each sprint, the day doesnt have to be specified. Obviously we cant leave it to the end of the sprint, but the earlier on in the sprint, the better

**Comment by SeanCraig** [comment]
I think it's important that as part of the 1-2-1 a look forward to the coming sprint should occur and so this should take place either on the first day or prior to that. Allow some flexibility but bake in some consistency.

**Comment by arctangent** [comment]
Resolution:

* Made minor edits to bring main document in line with quick guides
