### ISSUE TITLE
Line Management - documentation?

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#36]
Feedback on section 3.4.2:

> Are we expected to document these things or is a conversation enough?

**Comment by arctangent** [comment]
It is best practice to take notes in all meetings. This is especially important in line management meetings (either as the manager or as the report).

Proposed action:

* Feed back that yes, it would be a good idea to keep meeting notes
* Update 3.4.2 to make clear that anything to do with objectives should be recorded on the corporate system

**Comment by sikanderakbarali** [comment]
We can add comments via the learning pool by setting up check ins and taking notes in the meetings. These notes will allow you to go back and see what you discussed in previous 1-2-1s
