### ISSUE TITLE
Alignment with corporate performance system

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#37]
Feedback on section 4:

> Guidance re corporate seems to be check-ins once per month? How does 2 weekly align with that?

**Comment by arctangent** [comment]
The majority of staff in NHSD do not work in two-week iterations like NHSUK software developers do. To those other staff, a monthly meeting cycle makes sense (and is a big improvement over the previous annual meeting cycle). Within NHSUK it makes more sense to meet fortnightly as we have described in TWWW. The corporate system can be updated with relevant information every two weeks.

Proposed action:

* Update section 4 to explain the requirement and the reasoning

**Comment by sikanderakbarali** [comment]
I agree with @arctangent that we should have check ins every 2 weeks as this will allow users to review their objectives and allow us prinicpals to get involved if their are any blockers stopping you from achieving your objectives
