### ISSUE TITLE
Difficulty of objectives and pay progression

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#38]
Feedback:

> You have talked recently about OKRs and if we achieve a lot more than 70% then the objectives are too easy. A concern was raised about how this might affect the recent changes to the pay progression process. This process is now in place for everyone, according to a page published on the intranet in March 2020 (https://hscic365.sharepoint.com/HumanResources/Pages/Pay-award-and-.aspx). Do you know any more about the pay progression process, such as what and who is involved in the “pay step review”, mentioned in the above page, and how a “score” of 70% might affect pay progression?

**Comment by arctangent** [comment]
As far as I am aware the corporate requirement is only that a member of staff participates in the performance management process (i.e. completes their PDRs and has the required meetings documented on the new system). I don't anticipate that the requirements will get any stricter any time soon.

Proposed action:

* Clarify in TWWW that we expect each objective to have about 4 key results and that the 4th key result should be the "stretch target" i.e. 3 out of 4 is considered good enough. (The current guidance around quarterly PDRs suggests 3 objectives each with 4 key results so this would not be a big change)

**Comment by SeanCraig** [comment]
I think people should have ambitious objectives, tempered with achievable key results. I'm also not aware of any extra requirements. I would hope that if the "pay step review" became a thing it would look at the value of what people have achieved rather than a tick box exercise
