### ISSUE TITLE
What is 20% Time?

### ISSUE THREAD

**Issue by arctangent** [arctangent-nhsuk/the-way-we-work#39]
Feedback:

> you described [20% Time] as including continuous improvement work, training and personal development, and also possibly work within teams. Previously 20% time was understood to be only about continuous improvement, with separate time allowed for training and personal development, and was separate from any work carried out by teams. Is the nature of 20% time changing?

**Comment by arctangent** [comment]
We did make this distinction in the past, so that there was 2 hours for training and then an additional day per week on average for continuous improvement work.

However, the new view is that 20% time is the time used to work on one's OKRs. These OKRs can/should include training goals as well as development activities (possibly both at the same time), and ideally the OKRs agreed will be useful to the team's wider mission.

Proposed action:

* Consider renaming "20% Time" to "OKR Time" to reflect the new emphasis
* Clarify TWWW to make clear what the time is to be used for
* Produce a "Quick Guide to OKRs" including examples of good/bad choice of OKRs in particular team circumstances

**Comment by SeanCraig** [comment]
Agree but maybe "Improvement Time" or something else or less seriously even "Hammer Time" :)

**Comment by snehal-vahule** [comment]
DIY (Develoment in yourself ) time :)

**Comment by arctangent** [comment]
Resolution:

* DTLT agreed to "Quality Time"

**Comment by arctangent** [comment]
Closed by:

- https://github.com/arctangent-nhsuk/the-way-we-work/commit/96b4adfdbdac9284320619208d8482564b6b9747
- https://github.com/arctangent-nhsuk/the-way-we-work/commit/ace2383d2e93aa0b0b1b3c3fbed61a5f15354d69
