### ISSUE TITLE
3.1.3 Engineering Quality Framework

### ISSUE THREAD

**Issue by snehal-vahule** [arctangent-nhsuk/the-way-we-work#6]
Tools & Methods

> SonarQube for Dependency scanning, Security code analysis, Code coverage, Duplicate code scan, Code smells, Dead code scan

> GitLeaks for secret scanning

> Performance testing including Capacity tests, Stress tests, Soak tests,

> Chaos testing

**Comment by arctangent** [comment]
These are useful tools but I think this list needs to go in a standards document rather than in The Way We Work
